version: 2

models:
  - name: dim_orgs
    columns:
      - name: org_id
        tests:
          - not_null
          - unique
        tags: ['primary-key']
  - name: fct_monthly_financials
    latest_version: 1
    access: public
    config:
      contract:
        enforced: true
    columns:
      - name: date_month
        data_type: timestamp
        constraints:
          - type: not_null
        tests:
          - unique
        tags: ['primary-key']
      - name: cnt_subscribers
        data_type: integer
        constraints:
          - type: not_null
      - name: sum_revenue
        data_type: integer
        constraints:
          - type: not_null
    versions:
      - v: 1
        # config:
        #   alias: fct_monthly_financials
        # Matches what's above -- nothing more needed
    
      - v: 2
        # Removed a column -- this is the breaking change!
        columns:
          # This means: use the 'columns' list from above, but exclude country_name
        - name: cnt_subscribers
          data_type: text
          constraints:
            - type: not_null
      
  - name: fct_yearly_financials
    columns:
      - name: date_year
        tests:
          - not_null
          - unique
        tags: ['primary-key']
